package tj.esthata.newsapp.others

class ApiConfig {
    companion object {
        const val q = "q"
        const val qInTitle = "qInTitle"
        const val sources = "sources"
        const val domains = "domains"
        const val excludeDomains = "excludeDomains"
        const val from = "from"
        const val to = "to"
        const val language = "language"
        const val languageAR = "ar"
        const val languageDE = "de"
        const val languageEN = "en"
        const val languageES = "es"
        const val languageFR = "fr"
        const val languageHE = "he"
        const val languageIT = "it"
        const val languageNL = "nl"
        const val languageNO = "no"
        const val languagePT = "pt"
        const val languageRU = "ru"
        const val languageSE = "se"
        const val languageUD = "ud"
        const val languagZH = "zh"
        const val sortBy = "sortBy"
        const val sortByRelevancy = "relevancy"
        const val sortByPopularity = "popularity"
        const val sortByPublishedAt = "publishedAt"
        const val status = "status"
        const val statusOK = "ok"
        const val statusError = "error"
        const val countryUS = "us"
        const val countryRU = "ru"
    }
}